name: Build and Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      - name: Run tests
        run: go test ./...

  build-and-release:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Set version
        id: set_version
        run: |
          VERSION="${{ github.ref_name }}"
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          elif [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="dev"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install mingw-w64 for Windows cgo
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build binaries
        run: |
          mkdir -p dist
          # Linux x86_64
          GOOS=linux GOARCH=amd64 go build -ldflags "-X 'main.Version=${VERSION}'" -o dist/moksarab-linux-x86_64_${VERSION}
          # Linux arm64
          GOOS=linux GOARCH=arm64 go build -ldflags "-X 'main.Version=${VERSION}'" -o dist/moksarab-linux-arm64_${VERSION}
          # Windows x86_64 (cgo enabled)
          CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -ldflags "-X 'main.Version=${VERSION}'" -o dist/moksarab-windows-x86_64_${VERSION}.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
